version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: students
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mysql
